name: Publish to Maven Central

on:
  release:
    types: [ created ]

jobs:
  publish:
    name: Build, Publish, Release Artifacts
    runs-on: ubuntu-latest

    steps:
      # Step 1
      # This is optional and only if you want to set the timezone
      - name: Setup timezone
        run: |
          sudo timedatectl set-timezone Europe/Oslo
          timedatectl

      # Step 2
      # Required step
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 3
      # Optional step
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      # Step 4
      # Reguired step
      - name: Set up Java 21 JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          architecture: x64
          cache: 'gradle'
          check-latest: true

      # Step 5
      # Optional step, but recommended as user often commit the gradle wrapper jar without execute permissions.
      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Step 6
      - name: Stage publication locally
        run: ./gradlew publish --info

      # Step 7
      - name: Publish artifacts to Maven Central with JReleaser Gradle plugin
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          JRELEASER_BRANCH: master
        run: ./gradlew jreleaserFullRelease --warn --stacktrace

      # Persist logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
